### ISSUE TITLE
Is this the development repository since Indigo for openrtm_aist?

### ISSUE THREAD

**Issue by 130s** [tork-a/openrtm_aist-release#2]
I'm gradually making releases of hiro-nxo packages into Indigo, and would like to confirm the upstream resource chain is ok. I found the [doc and source job of openrtm_aist is not yet available](https://github.com/ros/rosdistro/blob/41cb86d30dccc4fa6a08b26531a170daac6ce94f/indigo/distribution.yaml#L4745) and I don't know where is its devel repo. Is it here or somewhere else?

**Comment by k-okada** [comment]
same as https://github.com/start-jsk/rtshell_core/issues/43, and I want to
release from this release package on hydro too, to use exactly same package
for both hydro/indigo.

--
◉ Kei Okada

**Comment by 130s** [comment]
I understand.

So my question in this ticket was where are documents and source repository, but the repository URL is already mentioned in the description in package.xml, which appears on Indigo's wiki. So I think that's enough.
